config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end


  
  post ':username/follow_user',  to: 'relationships#follow_user', 
                                    as: :follow_user

  post ':username/unfollow_user',  to: 'relationships#unfollow_user', 
                                      as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', 
                                        as: :link_through
    
  get 'notifications' => 'notifications#index'

  get 'profiles/show'
  
  devise_for :users,
             :controllers => { :registrations => "my_devise/registrations" }
  
  get 'browse', to: 'posts#browse', as: :browse_posts
    
  get ':username', to: 'profiles#show', as: :profile 
  
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root 'posts#index'
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  
  def show
    @posts = User.find_by(username: params[:username]).posts.order('created_at DESC')
  end
  
  def edit
  end
  
  def update
    @user.update(profile_params)
    if @user.save
      flash[:success] = "Profile updated"
      redirect_to profile_path(@user.username)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end
  
  private
  
    def set_user
      @user = User.find_by(username: params[:username])
    end
  
    def profile_params
      params.require(:user).permit(:avatar, :bio)
    end
  
    def correct_user
      unless current_user == @user
        flash[:alert]="That profile doesn't belong to you!"
        redirect_to root_path
      end
    end
end
  

app/helpers/profiles_helper.rb
module ProfilesHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio</h4>
              </div>
              <%= f.text_area :bio, label: false, rows: 4, cols: 99 %>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.username %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.username), 
              class: 'btn edit-button' %>
          <% else %>
            <% if current_user_is_following(current_user.id, @user.id) %>
              <%= link_to 'Following', unfollow_user_path, remote: true,
                class: 'btn unfollow-button', id: 'unfollow-button', 
                method: :post %>
            <% else %>
              <%= link_to 'Follow', follow_user_path, remote: true,
                class: 'btn follow-button', id: 'unfollow-button', 
                method: :post %>
            <% end %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics text-center">
        <ul class="list-inline list-unstyled">
          <li>
            <strong><%= @user.posts.count %></strong> 
            <%= "post".pluralize(@user.posts.count)%>
          </li>
          <li>
            <strong><%= @user.followers.count %></strong> 
            <%= "follower".pluralize(@user.followers.count)%>
          </li>
          <li>
            <strong><%= @user.following.count %></strong> 
            <%= "following" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>