config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end


  
  post ':username/follow_user',  to: 'relationships#follow_user', 
                                    as: :follow_user

  post ':username/unfollow_user',  to: 'relationships#unfollow_user', 
                                      as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', 
                                        as: :link_through
    
  get 'notifications' => 'notifications#index'

  get 'profiles/show'
  
  devise_for :users,
             :controllers => { :registrations => "my_devise/registrations" }
  
  get 'browse', to: 'posts#browse', as: :browse_posts
    
  get ':username', to: 'profiles#show', as: :profile 
  
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root 'posts#index'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  
  def index 
    @comments = @post.comments.order("created_at ASC")
    
     respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end
  
  def new
    @comment = @post.comments.build
  end
    
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id =  current_user.id
    
    if @comment.save
      create_notification @post
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js 
      end
    else
      flash.now[:alert] = "Failed to create comment, please check your submission 
                            and try again"
      render new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
    @comment.destroy
    flash[:success] = "Comment deleted"
    redirect_to(:back)
  end
  
  private
  
  def create_notification(post)
    return if post.user == current_user
    Notification.create(user_id: post.user.id,
                        notified_by_id: current_user.id,
                        post_id: post.id,
                        identifier: @comment.id,
                        notice_type: 'comment')
  end
  
  def comment_params
    params.require(:comment).permit(:content)
  end
  
  def set_post
    @post = Post.find(params[:post_id])
  end
  
  def set_comment
    @comment=@post.comments.find(params[:id])
  end
  
  def correct_user
    unless @comment.user.id == current_user.id
      flash[:alert] = "That comment doesn't belong to you!"
      redirect_to :back
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment">
  <div class="user-name">
        <%= link_to comment.user.username, profile_path(comment.user.username) %>
      </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), method: :delete, data: 
      { confirm: "Delete this comment?" } do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/index.html.erb
<%= render @comments, post: @post %>