config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end


  
  post ':username/follow_user',  to: 'relationships#follow_user', 
                                    as: :follow_user

  post ':username/unfollow_user',  to: 'relationships#unfollow_user', 
                                      as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', 
                                        as: :link_through
    
  get 'notifications' => 'notifications#index'

  get 'profiles/show'
  
  devise_for :users,
             :controllers => { :registrations => "my_devise/registrations" }
  
  get 'browse', to: 'posts#browse', as: :browse_posts
    
  get ':username', to: 'profiles#show', as: :profile 
  
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  
  patch ':username/edit', to: 'profiles#update', as: :update_profile

  root 'posts#index'
  
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Photogram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= render 'notifications/notification_dropdown' %>
          </li>
          <li>
            <%= link_to "Profile", profile_path(current_user.username) %>
          </li>
          <li>
            <%= link_to "Browse Posts", browse_posts_path %>
          </li>
          <li>
            <%= link_to "New Post", new_post_path %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
          <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
  <%= render 'layouts/navbar' %>
  
  <% flash.each do |message_type, message| %>
    <div class="container">
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    </div>
  <% end %>
  
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>